import React from "react";
import { CrudPage, useRows } from "@/components/Crud";
import { useAuth } from "@/context/AuthContext";
import { clean } from "@/lib/clean";
import { fmtDate, today, titleCase } from "@/lib/fmt";
import { exportPDF } from "@/lib/exports";
import { Button } from "@/components/ui/button";
import { FileText } from "lucide-react";
import { toast } from "sonner";

const WEATHER = ["Clear", "Cloudy", "Light Rain", "Heavy Rain", "Very Hot", "Windy", "Storm"];

export default function SiteReports() {
  const { profile } = useAuth();
  const { data: projects } = useRows("projects", { order: { column: "name", ascending: true } });
  const pname = (id) => projects?.find((p) => p.id === id)?.name || "—";

  const pdf = (r) => {
    const project = projects?.find((p) => p.id === r.project_id);
    exportPDF({
      filename: `PMC-${r.report_no}`,
      title: `DAILY SITE REPORT ${r.report_no}`,
      meta: [
        `Project: ${project?.name || "—"}${project?.code ? ` (${project.code})` : ""}`,
        `Date: ${fmtDate(r.date)}`,
        `Weather: ${r.weather || "—"}`,
        `Workers present: ${r.workers_present}`,
        `Generated by: ${profile?.full_name || "—"}`,
      ],
      columns: [{ key: "section", label: "Section" }, { key: "detail", label: "Detail" }],
      rows: [
        { section: "Work completed", detail: r.work_completed || "—" },
        { section: "Materials received", detail: r.materials_received || "—" },
        { section: "Materials consumed", detail: r.materials_consumed || "—" },
        { section: "Equipment used", detail: r.equipment_used || "—" },
        { section: "Transportation", detail: r.transportation_note || "—" },
        { section: "Expenses", detail: r.expenses_note || "—" },
        { section: "Issues", detail: r.issues || "—" },
        { section: "Delays", detail: r.delays || "—" },
        { section: "Notes", detail: r.notes || "—" },
      ],
      totals: [{ label: "Workers present", value: String(r.workers_present) }],
    });
    toast.success("Daily Site Report PDF generated.");
  };

  return (
    <CrudPage
      table="daily_site_reports"
      module="sitereports"
      title="Daily Site Reports"
      subtitle="One report per project per day — weather, work done, materials, issues, delays and site photo"
      searchKeys={["report_no", "work_completed", "issues", "weather"]}
      order={{ column: "date", ascending: false }}
      addLabel="New Report"
      fields={[
        { name: "project_id", label: "Project", lookup: { table: "projects" }, required: true },
        { name: "date", label: "Date", type: "date", required: true, default: today },
        { name: "weather", label: "Weather", type: "select", options: WEATHER, default: "Clear" },
        { name: "workers_present", label: "Workers Present", type: "number", step: "1", default: 0 },
        { name: "work_completed", label: "Work Completed", type: "textarea", full: true, required: true },
        { name: "materials_received", label: "Materials Received", type: "textarea", full: true },
        { name: "materials_consumed", label: "Materials Consumed", type: "textarea", full: true },
        { name: "equipment_used", label: "Equipment Used", type: "textarea", full: true },
        { name: "transportation_note", label: "Transportation", type: "textarea", full: true },
        { name: "expenses_note", label: "Expenses", type: "textarea", full: true },
        { name: "issues", label: "Issues", type: "textarea", full: true },
        { name: "delays", label: "Delays", type: "textarea", full: true },
        { name: "photo_url", label: "Site Photo", type: "file", folder: "site-reports", full: true },
        { name: "notes", label: "Notes", type: "textarea", full: true },
      ]}
      buildPayload={(v) => clean(v, { numbers: ["workers_present"] })}
      detail={(r) => ({
        title: "Daily Site Report",
        amount: 0,
        receipt: r.photo_url,
        rows: [
          { label: "Project", text: pname(r.project_id) },
          { label: "Weather", text: r.weather },
          { label: "Workers Present", text: String(r.workers_present) },
          { label: "Work Completed", text: r.work_completed },
          { label: "Materials Received", text: r.materials_received },
          { label: "Materials Consumed", text: r.materials_consumed },
          { label: "Equipment", text: r.equipment_used },
          { label: "Transportation", text: r.transportation_note },
          { label: "Expenses", text: r.expenses_note },
          { label: "Issues", text: r.issues },
          { label: "Delays", text: r.delays },
        ],
      })}
      columns={[
        { key: "report_no", label: "Report", render: (r) => <span className="mono text-xs text-primary">{r.report_no}</span> },
        { key: "date", label: "Date", render: (r) => fmtDate(r.date) },
        { key: "project_id", label: "Project", render: (r) => pname(r.project_id) },
        { key: "weather", label: "Weather", render: (r) => titleCase(r.weather) },
        { key: "workers_present", label: "Workers" },
        { key: "issues", label: "Issues", render: (r) => (r.issues ? <span className="text-destructive">Reported</span> : "—") },
      ]}
      rowExtra={(r) => (
        <Button size="icon" variant="ghost" onClick={() => pdf(r)} data-testid={`dsr-pdf-${r.id}`}><FileText className="h-4 w-4" /></Button>
      )}
    />
  );
}
