import React, { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase, friendly } from "@/lib/supabase";
import { useAuth } from "@/context/AuthContext";
import { useFinance, projectStats, ledgerBalances } from "@/lib/finance";
import { useRows, DataTable, RecordForm } from "@/components/Crud";
import { money, shortMoney, fmtDate, num, titleCase, EXPENSE_CATEGORIES, BRAND } from "@/lib/fmt";
import { clean } from "@/lib/clean";
import { exportPDF, exportExcel, exportCSV } from "@/lib/exports";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { ArrowLeft, Plus, FileText, FileSpreadsheet, FileDown } from "lucide-react";

const Stat = ({ label, value, tone, testId }) => (
  <div className="panel p-4" data-testid={testId}>
    <p className="label-xs">{label}</p>
    <p className={`stat-value mt-1.5 ${tone === "good" ? "text-accent" : tone === "bad" ? "text-destructive" : tone === "primary" ? "text-primary" : ""}`}>{value}</p>
  </div>
);

export default function ProjectDetail() {
  const { id } = useParams();
  const { can, profile } = useAuth();
  const qc = useQueryClient();
  const { data, isLoading } = useFinance();
  const { data: budgets } = useRows("project_budgets", { eq: { project_id: id }, order: { column: "created_at", ascending: true } });
  const [budgetOpen, setBudgetOpen] = useState(false);
  const [catOpen, setCatOpen] = useState(null);

  const saveBudget = useMutation({
    mutationFn: async (v) => {
      const c = clean(v, { numbers: ["budget_amount"] });
      const { error } = await supabase.from("project_budgets").insert({ ...c, project_id: id });
      if (error) throw error;
      await supabase.from("audit_logs").insert({ action: "created", table_name: "project_budgets", project_id: id, user_name: profile?.full_name, new_value: c });
    },
    onSuccess: () => { toast.success("Budget saved."); setBudgetOpen(false); qc.invalidateQueries(); },
    onError: (e) => toast.error(friendly(e, "Unable to save budget.")),
  });

  if (isLoading || !data) return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[...Array(8)].map((_, i) => <Skeleton key={i} className="h-24 rounded-2xl" />)}</div>;
  const s = projectStats(data, id);
  if (!s.project) return <div className="panel p-8 text-center"><p className="font-display text-lg">Project not found</p><Link to="/projects" className="mt-2 inline-block text-sm text-primary">Back to projects</Link></div>;

  const p = s.project;
  const led = ledgerBalances(data, id);
  const ex = data.expenses.filter((e) => e.project_id === id);
  const inc = data.incomes.filter((e) => e.project_id === id);
  const workers = data.workers.filter((w) => w.project_id === id && !w.archived_at);
  const purchases = data.purchases.filter((x) => x.project_id === id);
  const trans = (data.transportation || []).filter((x) => x.project_id === id);
  const catExpenses = catOpen ? ex.filter((e) => e.work_category_id === catOpen.id) : [];

  const budgetFor = (workCatId, expCat) =>
    (budgets || []).filter((b) => (workCatId ? b.work_category_id === workCatId : b.expense_category === expCat))
      .reduce((a, b) => a + Number(b.budget_amount || 0), 0);

  const reportMeta = [`Project: ${p.name} (${p.code})`, `Client: ${p.client_name || "—"}`, `Report date: ${fmtDate(new Date())}`, `Generated by: ${profile?.full_name || "—"}`];
  const exportRows = ex.map((e) => ({ Ref: e.ref_no, Date: e.date, Category: e.category, Description: e.description, Amount: Number(e.amount), Method: e.payment_method }));

  return (
    <div className="space-y-5 fade-up">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <Link to="/projects" className="mb-1 flex items-center gap-1.5 text-xs text-muted-foreground hover:text-primary" data-testid="back-to-projects">
            <ArrowLeft className="h-3.5 w-3.5" /> Projects
          </Link>
          <h1 className="font-display text-2xl font-bold sm:text-3xl" data-testid="project-name">{p.name}</h1>
          <p className="mono mt-1 text-xs text-primary">{p.code} · <span className="capitalize text-muted-foreground">{String(p.status).replace("_", " ")}</span>{p.archived_at ? " · archived (read-only)" : ""}</p>
        </div>
        <div className="panel px-4 py-3 text-right">
          <p className="label-xs">Project Health</p>
          <p className="stat-value text-primary" data-testid="project-health">{s.health}/100</p>
          <p className="text-xs text-muted-foreground">{s.health >= 80 ? "Good" : s.health >= 60 ? "Fair" : "Needs attention"}</p>
        </div>
      </div>

      <Tabs defaultValue="overview">
        <TabsList className="flex-wrap">
          <TabsTrigger value="overview" data-testid="tab-overview">Overview</TabsTrigger>
          <TabsTrigger value="work" data-testid="tab-work">Work</TabsTrigger>
          <TabsTrigger value="financial" data-testid="tab-financial">Financial</TabsTrigger>
          <TabsTrigger value="resources" data-testid="tab-resources">Resources</TabsTrigger>
          <TabsTrigger value="reports" data-testid="tab-reports">Reports</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="mt-4 space-y-4">
          <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
            <Stat testId="pd-contract" label="Contract Amount" value={money(s.contract)} tone="primary" />
            <Stat testId="pd-received" label="Received" value={money(s.received)} tone="good" />
            <Stat testId="pd-expenses" label="Expenses" value={money(s.expenses)} tone="bad" />
            <Stat testId="pd-deductions" label="Deductions" value={money(s.deductions)} />
            <Stat testId="pd-balance" label="Available Balance" value={money(s.balance)} />
            <Stat testId="pd-outstanding" label="Outstanding from Client" value={money(s.outstanding)} />
            <Stat testId="pd-estprofit" label="Estimated Profit" value={money(s.estimatedProfit)} tone={s.estimatedProfit >= 0 ? "good" : "bad"} />
            <Stat testId="pd-actprofit" label="Actual Profit" value={money(s.actualProfit)} tone={s.actualProfit >= 0 ? "good" : "bad"} />
          </div>
          <div className="panel p-4">
            <div className="mb-2 flex items-center justify-between"><p className="label-xs">Progress</p><span className="text-sm">{p.progress}%</span></div>
            <Progress value={p.progress} className="h-2" />
            <div className="mt-4 grid gap-3 text-sm sm:grid-cols-4">
              <div><p className="label-xs">Location</p><p>{p.location || "—"}</p></div>
              <div><p className="label-xs">Start</p><p>{fmtDate(p.start_date)}</p></div>
              <div><p className="label-xs">Expected</p><p>{fmtDate(p.expected_completion)}</p></div>
              <div><p className="label-xs">Client</p><p>{p.client_name || "—"}</p></div>
            </div>
          </div>
          <div className="panel p-4">
            <p className="label-xs mb-3">Cost forecasting</p>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              <div><p className="label-xs">Current Cost</p><p className="mono">{shortMoney(s.expenses)}</p></div>
              <div><p className="label-xs">Expected Remaining</p><p className="mono">{shortMoney(s.remainingCost)}</p></div>
              <div><p className="label-xs">Expected Final</p><p className="mono">{shortMoney(s.forecastFinalCost)}</p></div>
              <div><p className="label-xs">Forecast Profit</p><p className="mono text-primary">{shortMoney(s.estimatedProfit)}</p></div>
            </div>
          </div>
        </TabsContent>

        <TabsContent value="work" className="mt-4 space-y-4">
          <div className="flex items-center justify-between">
            <p className="label-xs">Work categories · budget vs spent</p>
            {can("projects", "w") && !p.archived_at && (
              <Button size="sm" variant="secondary" onClick={() => setBudgetOpen(true)} data-testid="add-budget-btn"><Plus className="mr-1 h-3.5 w-3.5" /> Set Budget</Button>
            )}
          </div>
          <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
            {s.byWork.map((w) => {
              const budget = budgetFor(w.id);
              const pct = budget ? (w.spent / budget) * 100 : 0;
              return (
                <button key={w.id} onClick={() => setCatOpen(w)} data-testid={`work-cat-${w.id}`}
                  className="rounded-2xl border border-border/70 bg-secondary/30 p-4 text-left transition-colors hover:border-primary/50">
                  <div className="flex items-start justify-between gap-2">
                    <p className="font-display font-semibold">{w.name}</p>
                    {budget > 0 && (
                      <span className={`rounded-full px-2 py-0.5 text-[10px] uppercase ${pct >= 100 ? "bg-destructive/20 text-destructive" : pct >= 90 ? "bg-destructive/15 text-destructive" : pct >= 75 ? "bg-primary/20 text-primary" : "bg-accent/15 text-accent"}`}>
                        {pct >= 100 ? "Exceeded" : pct >= 90 ? "Critical" : pct >= 75 ? "Warning" : "On track"}
                      </span>
                    )}
                  </div>
                  <div className="mt-3 grid grid-cols-2 gap-2 text-xs">
                    <div><p className="label-xs">Budget</p><p className="mono">{budget ? money(budget) : "—"}</p></div>
                    <div><p className="label-xs">Spent</p><p className="mono text-destructive">{money(w.spent)}</p></div>
                    <div><p className="label-xs">Remaining</p><p className="mono">{budget ? money(budget - w.spent) : "—"}</p></div>
                    <div><p className="label-xs">Transactions</p><p>{w.count}</p></div>
                    <div><p className="label-xs">Labor</p><p className="mono">{shortMoney(w.labor)}</p></div>
                    <div><p className="label-xs">Materials</p><p className="mono">{shortMoney(w.materials)}</p></div>
                    <div><p className="label-xs">Transport</p><p className="mono">{shortMoney(w.transportation)}</p></div>
                    <div><p className="label-xs">Other</p><p className="mono">{shortMoney(w.other)}</p></div>
                  </div>
                  {budget > 0 && <Progress value={Math.min(pct, 100)} className="mt-3 h-1.5" />}
                </button>
              );
            })}
          </div>
          <div className="panel p-4">
            <p className="label-xs mb-3">Category budgets</p>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              {EXPENSE_CATEGORIES.map((c) => {
                const b = budgetFor(null, c);
                const spent = s.byCategory[c] || 0;
                const pct = b ? (spent / b) * 100 : 0;
                return (
                  <div key={c} className="rounded-xl bg-secondary/40 p-3" data-testid={`cat-budget-${c}`}>
                    <p className="text-sm capitalize">{c}</p>
                    <p className="mono text-xs text-muted-foreground">{money(spent)} / {b ? money(b) : "no budget"}</p>
                    {b > 0 && <Progress value={Math.min(pct, 100)} className="mt-2 h-1" />}
                  </div>
                );
              })}
            </div>
          </div>
        </TabsContent>

        <TabsContent value="financial" className="mt-4 space-y-4">
          <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
            <Stat label="Cash" value={money(led.cash)} testId="pd-cash" />
            <Stat label="UPI" value={money(led.upi)} testId="pd-upi" />
            <Stat label="Bank" value={money(led.bank)} testId="pd-bank" />
            <Stat label="Profit / Loss" value={money(s.received - s.expenses - s.deductions)} tone={s.received - s.expenses >= 0 ? "good" : "bad"} testId="pd-pl" />
          </div>
          <p className="label-xs">Income</p>
          <DataTable testId="pd-income-table" rows={inc} empty="No income recorded for this project"
            columns={[
              { key: "ref_no", label: "Ref", render: (r) => <span className="mono text-xs text-primary">{r.ref_no}</span> },
              { key: "date", label: "Date", render: (r) => fmtDate(r.date) },
              { key: "received_from", label: "From", render: (r) => r.received_from || "—" },
              { key: "payment_method", label: "Method", render: (r) => titleCase(r.payment_method) },
              { key: "amount", label: "Amount", render: (r) => <span className="mono text-accent">{money(r.amount)}</span> },
            ]} />
          <p className="label-xs">Expenses</p>
          <DataTable testId="pd-expense-table" rows={ex} empty="No expenses recorded for this project"
            columns={[
              { key: "ref_no", label: "Ref", render: (r) => <span className="mono text-xs text-primary">{r.ref_no}</span> },
              { key: "date", label: "Date", render: (r) => fmtDate(r.date) },
              { key: "category", label: "Category", render: (r) => <span className="capitalize">{r.category}</span> },
              { key: "description", label: "Description", render: (r) => r.description || "—" },
              { key: "amount", label: "Amount", render: (r) => <span className="mono text-destructive">{money(r.amount)}</span> },
            ]} />
        </TabsContent>

        <TabsContent value="resources" className="mt-4 space-y-4">
          <p className="label-xs">Workers on this project ({workers.length})</p>
          <DataTable testId="pd-workers-table" rows={workers} empty="No workers assigned"
            columns={[
              { key: "name", label: "Worker" },
              { key: "worker_type", label: "Type" },
              { key: "daily_wage", label: "Daily Wage", render: (r) => <span className="mono">{money(r.daily_wage)}</span> },
              { key: "phone", label: "Phone", render: (r) => r.phone || "—" },
            ]} />
          <p className="label-xs">Material purchases ({purchases.length})</p>
          <DataTable testId="pd-purchase-table" rows={purchases} empty="No purchases recorded"
            columns={[
              { key: "ref_no", label: "PO", render: (r) => <span className="mono text-xs text-primary">{r.ref_no}</span> },
              { key: "date", label: "Date", render: (r) => fmtDate(r.date) },
              { key: "quantity", label: "Qty", render: (r) => `${num(r.quantity, 3)} ${r.unit || ""}` },
              { key: "total", label: "Total", render: (r) => <span className="mono">{money(r.total)}</span> },
            ]} />
          <p className="label-xs">Transportation ({trans.length})</p>
          <DataTable testId="pd-transport-table" rows={trans} empty="No transportation recorded"
            columns={[
              { key: "date", label: "Date", render: (r) => fmtDate(r.date) },
              { key: "vehicle", label: "Vehicle" },
              { key: "trips", label: "Trips" },
              { key: "total", label: "Total", render: (r) => <span className="mono">{money(r.total)}</span> },
            ]} />
        </TabsContent>

        <TabsContent value="reports" className="mt-4 space-y-3">
          <p className="text-sm text-muted-foreground">Branded exports for {p.name} — {BRAND.name} · {BRAND.by}</p>
          <div className="flex flex-wrap gap-2">
            <Button data-testid="pd-export-pdf" onClick={() => exportPDF({
              filename: `PMC-${p.code}-Project-Report`, title: "Project Financial Report", meta: reportMeta,
              columns: [{ key: "Head", label: "Head" }, { key: "Amount", label: "Amount" }],
              rows: [
                { Head: "Contract Amount", Amount: money(s.contract) }, { Head: "Received", Amount: money(s.received) },
                { Head: "Expenses", Amount: money(s.expenses) }, { Head: "Deductions", Amount: money(s.deductions) },
                { Head: "Available Balance", Amount: money(s.balance) }, { Head: "Outstanding", Amount: money(s.outstanding) },
                ...Object.entries(s.byCategory).map(([k, v]) => ({ Head: `Expense · ${titleCase(k)}`, Amount: money(v) })),
              ],
              totals: [{ label: "Actual Profit", value: money(s.actualProfit) }, { label: "Estimated Profit", value: money(s.estimatedProfit) }, { label: "Project Health", value: `${s.health}/100` }],
            })}><FileText className="mr-1.5 h-4 w-4" /> Project Report PDF</Button>
            <Button variant="secondary" data-testid="pd-export-expense-pdf" onClick={() => exportPDF({
              filename: `PMC-${p.code}-Expense-Report`, title: "Expense Report", meta: reportMeta,
              columns: [{ key: "Ref", label: "Ref" }, { key: "Date", label: "Date" }, { key: "Category", label: "Category" }, { key: "Description", label: "Description" }, { key: "Amount", label: "Amount" }, { key: "Method", label: "Method" }],
              rows: exportRows, totals: [{ label: "Total Expenses", value: money(s.expenses) }],
            })}><FileText className="mr-1.5 h-4 w-4" /> Expense Report PDF</Button>
            <Button variant="secondary" data-testid="pd-export-excel" onClick={() => exportExcel(`PMC-${p.code}-Expenses`, exportRows, "Expenses")}>
              <FileSpreadsheet className="mr-1.5 h-4 w-4" /> Excel
            </Button>
            <Button variant="secondary" data-testid="pd-export-csv" onClick={() => exportCSV(`PMC-${p.code}-Expenses`, exportRows)}>
              <FileDown className="mr-1.5 h-4 w-4" /> CSV
            </Button>
          </div>
        </TabsContent>
      </Tabs>

      <RecordForm open={budgetOpen} onOpenChange={setBudgetOpen} title="Set Budget" submitting={saveBudget.isPending}
        onSubmit={(v) => saveBudget.mutate(v)}
        fields={[
          { name: "work_category_id", label: "Work Category (optional)", lookup: { table: "work_categories" } },
          { name: "expense_category", label: "Expense Category (optional)", type: "select", options: EXPENSE_CATEGORIES },
          { name: "budget_amount", label: "Budget Amount (₹)", type: "number", required: true, min: 0 },
        ]} />

      {catOpen && (
        <div className="panel p-4" data-testid="work-cat-transactions">
          <div className="mb-3 flex items-center justify-between">
            <p className="label-xs">Transactions · {catOpen.name}</p>
            <Button size="sm" variant="ghost" onClick={() => setCatOpen(null)} data-testid="close-work-cat">Close</Button>
          </div>
          <DataTable rows={catExpenses} empty="No transactions in this work category"
            columns={[
              { key: "ref_no", label: "Ref", render: (r) => <span className="mono text-xs text-primary">{r.ref_no}</span> },
              { key: "date", label: "Date", render: (r) => fmtDate(r.date) },
              { key: "category", label: "Category", render: (r) => <span className="capitalize">{r.category}</span> },
              { key: "description", label: "Description", render: (r) => r.description || "—" },
              { key: "amount", label: "Amount", render: (r) => <span className="mono">{money(r.amount)}</span> },
            ]} />
        </div>
      )}
    </div>
  );
}
